Update azure-pipelines-for-deploy.yml for Azure Pipelines

diff --git a/azure-pipelines-for-deploy.yml b/azure-pipelines-for-deploy.yml
--- a/azure-pipelines-for-deploy.yml
+++ b/azure-pipelines-for-deploy.yml
@@ -40,3 +40,58 @@ steps:
     helm upgrade --install tomcat app2/helm_chart 
   workingDirectory: $(Working_Directory)
   displayName: 'Deploy second application'
+
+- script: |
+    # Сheck Helm status
+    set -e
+    RELEASES=("ingress" "nginx" "tomcat")
+    for release in "${RELEASES[@]}"; do
+      STATUS=$(helm status $release -o json | jq -r '.info.status')
+      if [ "$STATUS" != "deployed" ]; then
+        echo "Release $release is in $STATUS status, rolling back..."
+        helm rollback $release
+        exit 1
+      fi
+    done
+
+    - task: Bash@3
+      inputs:
+        targetType: 'inline'
+        script: |
+          #!/bin/bash
+          
+          BASE_URL="https://romanmarkov.org"
+          PATHS=(
+              "/app1"
+              "/app2"
+              "/port5000"
+              "/port6000"
+          )
+
+          check_path() {
+              local url=$1
+              local path=$2
+              echo "Проверка пути: $url$path"
+              
+              http_code=$(curl --write-out "%{http_code}" --silent --output /dev/null "$url$path")
+              
+              if [ "$http_code" -eq 200 ]; then
+                  echo "OK: $url$path $http_code"
+              else
+                  echo "ERROR: $url$path $http_code"
+                  if [ "$url$path" == "https://romanmarkov.org/app1" ]; then
+                    helm rollout restart deployment nginx --namespace default
+                  else
+                    helm rollout restart deployment tomcat --namespace default
+                  fi
+              fi
+          }
+          
+          for path in "${PATHS[@]}"; do
+              check_path $BASE_URL $path
+          done
+
+    echo "All services are deployed and accessible."
+
+  workingDirectory: $(Working_Directory)
+  displayName: 'Verify Deployment and Rollback if Necessary'
